#!/usr/bin/env bash
# configure a brand new NGINX server

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i "/listen 80 default_server;/a \trewrite ^/redirect_me https://www.youtube.com/shorts/Srj05lBrk84 permanent;" /etc/nginx/sites-available/default

ufw allow 'Nginx HTTP'
service nginx restart
