#!/usr/bin/env bash
# configure a load-balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.0

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend web_back
backend web_back
	mode http
	balance roundrobin
	server 44456-web-01 18.206.202.190:80 check
	server 44456-web-02 100.25.111.177:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
