#!/usr/bin/env bash
# configure a load-balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy=1.8.\*

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend web_back
backend web_back
	mode http
	balance roundrobin
	server 44456-web-01 54.221.180.0:80 check
	server 44456-web-02 100.27.14.142:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
