#!/usr/bin/env bash
# This program loops through and uses if,elif and else
i=1
while [ $((i++)) -le 10 ]; do
	if [ "$i" -eq "5" ]; then
		echo "bad luck"
	elif [ "$i" -eq "9" ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
