#!/usr/bin/env bash

sudo ufw enable
sudo ufw app list
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw status verbose
sudo ufw allow ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw logging off
sudo ufw status verbose
sudo ufw enable
